import crypto from 'node:crypto'
import type { SetupConfig } from '../types.js'
import { quoteEnvValue } from '../utils/env-quote.js'

function generateSecret(): string {
  return crypto.randomBytes(32).toString('base64')
}

export function generateEnvFile(config: SetupConfig): string {
  const protocol = config.useHttps ? 'https' : 'http'
  const portSuffix = (config.useHttps && config.httpPort === 443) || (!config.useHttps && config.httpPort === 80)
    ? ''
    : `:${config.httpPort}`
  const baseUrl = `${protocol}://${config.domain}${portSuffix}`
  const domainWithPort = `${config.domain}${portSuffix}`

  const topDomain = config.domain === 'localhost'
    ? 'localhost'
    : config.domain.split('.').slice(-2).join('.')

  const cookieDomain = config.domain === 'localhost'
    ? '.localhost'
    : `.${topDomain}`

  const nextAuthSecret = generateSecret()
  const jwtSecret = generateSecret()
  const collabInternalKey = generateSecret()

  const lines: string[] = [
    '# FuneralAcademy Environment Variables',
    '# Generated by FuneralAcademy CLI',
    '',
    '# =============================================================================',
    '# Domain & Hosting Configuration',
    '# =============================================================================',
    '',
    `FUNERALACADEMY_DOMAIN=${domainWithPort}`,
    `HTTP_PORT=${config.httpPort}`,
    '',
    '# =============================================================================',
    '# Frontend Environment Variables (NEXT_PUBLIC_*)',
    '# =============================================================================',
    '',
    `NEXT_PUBLIC_FUNERALACADEMY_API_URL=${baseUrl}/api/v1/`,
    `NEXT_PUBLIC_FUNERALACADEMY_BACKEND_URL=${baseUrl}/`,
    `NEXT_PUBLIC_FUNERALACADEMY_DOMAIN=${domainWithPort}`,
    `NEXT_PUBLIC_FUNERALACADEMY_TOP_DOMAIN=${topDomain}`,
    'NEXT_PUBLIC_FUNERALACADEMY_MULTI_ORG=False',
    `NEXT_PUBLIC_FUNERALACADEMY_DEFAULT_ORG=${config.orgSlug || 'default'}`,
    `NEXT_PUBLIC_FUNERALACADEMY_HTTPS=${config.useHttps ? 'True' : 'False'}`,
  ]

  if (config.unsplashEnabled && config.unsplashAccessKey) {
    lines.push(`NEXT_PUBLIC_UNSPLASH_ACCESS_KEY=${quoteEnvValue(config.unsplashAccessKey!)}`)
  }

  lines.push(
    '',
    '# =============================================================================',
    '# NextAuth Configuration',
    '# =============================================================================',
    '',
    `NEXTAUTH_URL=${baseUrl}`,
    `NEXTAUTH_SECRET=${nextAuthSecret}`,
  )

  if (config.googleOAuthEnabled && config.googleClientId && config.googleClientSecret) {
    lines.push(
      `FUNERALACADEMY_GOOGLE_CLIENT_ID=${quoteEnvValue(config.googleClientId!)}`,
      `FUNERALACADEMY_GOOGLE_CLIENT_SECRET=${quoteEnvValue(config.googleClientSecret!)}`,
    )
  }

  lines.push(
    '',
    '# =============================================================================',
    '# Backend Configuration',
    '# =============================================================================',
    '',
    `FUNERALACADEMY_SQL_CONNECTION_STRING=${config.useExternalDb
      ? quoteEnvValue(config.externalDbConnectionString!)
      : `postgresql://funeralacademy:${config.dbPassword}@db:5432/funeralacademy`}`,
    `FUNERALACADEMY_REDIS_CONNECTION_STRING=${config.useExternalRedis
      ? quoteEnvValue(config.externalRedisConnectionString!)
      : 'redis://redis:6379/funeralacademy'}`,
    `FUNERALACADEMY_COOKIE_DOMAIN=${cookieDomain}`,
    'FUNERALACADEMY_PORT=9000',
    '',
    '# =============================================================================',
    '# Security',
    '# =============================================================================',
    '',
    `FUNERALACADEMY_AUTH_JWT_SECRET_KEY=${jwtSecret}`,
    `FUNERALACADEMY_INITIAL_ADMIN_EMAIL=${quoteEnvValue(config.adminEmail)}`,
    `FUNERALACADEMY_INITIAL_ADMIN_PASSWORD=${quoteEnvValue(config.adminPassword)}`,
    `FUNERALACADEMY_INITIAL_ORG_NAME=${quoteEnvValue(config.orgName || 'Default Organization')}`,
    `FUNERALACADEMY_INITIAL_ORG_SLUG=${quoteEnvValue(config.orgSlug || 'default')}`,
    '',
    '# =============================================================================',
    '# Collaboration Server',
    '# =============================================================================',
    '',
    `COLLAB_INTERNAL_KEY=${collabInternalKey}`,
    `FUNERALACADEMY_REDIS_URL=${config.useExternalRedis
      ? config.externalRedisConnectionString
      : 'redis://redis:6379'}`,
    `NEXT_PUBLIC_COLLAB_URL=${config.useHttps ? 'wss' : 'ws'}://${config.domain}${portSuffix}/collab`,
    '',
    '# =============================================================================',
    '# General Settings',
    '# =============================================================================',
    '',
    'FUNERALACADEMY_DEVELOPMENT_MODE=False',
    'FUNERALACADEMY_LOGFIRE_ENABLED=False',
  )

  if (config.aiEnabled && config.geminiApiKey) {
    lines.push(
      '',
      '# =============================================================================',
      '# AI Configuration',
      '# =============================================================================',
      '',
      `FUNERALACADEMY_GEMINI_API_KEY=${config.geminiApiKey}`,
      'FUNERALACADEMY_IS_AI_ENABLED=True',
    )
  } else {
    lines.push(
      '',
      '# =============================================================================',
      '# AI Configuration',
      '# =============================================================================',
      '',
      'FUNERALACADEMY_IS_AI_ENABLED=False',
    )
  }

  if (config.emailEnabled) {
    const provider = config.emailProvider || 'resend'
    lines.push(
      '',
      '# =============================================================================',
      '# Email Configuration',
      '# =============================================================================',
      '',
      `FUNERALACADEMY_EMAIL_PROVIDER=${provider}`,
      `FUNERALACADEMY_SYSTEM_EMAIL_ADDRESS=${config.systemEmailAddress || `noreply@${config.domain}`}`,
    )

    if (provider === 'resend' && config.resendApiKey) {
      lines.push(`FUNERALACADEMY_RESEND_API_KEY=${config.resendApiKey}`)
    }

    if (provider === 'smtp') {
      if (config.smtpHost) lines.push(`FUNERALACADEMY_SMTP_HOST=${config.smtpHost}`)
      lines.push(`FUNERALACADEMY_SMTP_PORT=${config.smtpPort || 587}`)
      if (config.smtpUsername) lines.push(`FUNERALACADEMY_SMTP_USERNAME=${config.smtpUsername}`)
      if (config.smtpPassword) lines.push(`FUNERALACADEMY_SMTP_PASSWORD=${config.smtpPassword}`)
      lines.push(`FUNERALACADEMY_SMTP_USE_TLS=${config.smtpUseTls !== false ? 'True' : 'False'}`)
    }
  }

  if (config.s3Enabled && config.s3BucketName) {
    lines.push(
      '',
      '# =============================================================================',
      '# Content Delivery',
      '# =============================================================================',
      '',
      'FUNERALACADEMY_CONTENT_DELIVERY_TYPE=s3api',
      `FUNERALACADEMY_S3_API_BUCKET_NAME=${config.s3BucketName}`,
    )
    if (config.s3EndpointUrl) {
      lines.push(`FUNERALACADEMY_S3_API_ENDPOINT_URL=${config.s3EndpointUrl}`)
    }
  } else {
    lines.push(
      '',
      '# =============================================================================',
      '# Content Delivery',
      '# =============================================================================',
      '',
      'FUNERALACADEMY_CONTENT_DELIVERY_TYPE=filesystem',
    )
  }

  if (!config.useExternalDb) {
    lines.push(
      '',
      '# =============================================================================',
      '# Database Configuration',
      '# =============================================================================',
      '',
      'POSTGRES_USER=funeralacademy',
      `POSTGRES_PASSWORD=${config.dbPassword}`,
      'POSTGRES_DB=funeralacademy',
      '',
    )
  } else {
    lines.push('')
  }

  return lines.join('\n')
}
